### ISSUE TITLE
projit init fails in fresh python 3.13 intall

### ISSUE THREAD

**Issue by GeoffPidcock** [john-hawkins/projit#4]
Stack trace as follows, seems to missing a module called `pkg_resources`. Happy to have a try resolving this once we can confirm this issue. 

```python
projit init buildmas24 template=default

Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Users\geoff\dev\buildmas24\.env\Scripts\projit.exe\__main__.py", line 4, in <module>
    from projit.cli import main
  File "C:\Users\geoff\dev\buildmas24\.env\Lib\site-packages\projit\__init__.py", line 4, in <module>       
    from .projit import projit_load
  File "C:\Users\geoff\dev\buildmas24\.env\Lib\site-packages\projit\projit.py", line 16, in <module>        
    from .template import load_template
  File "C:\Users\geoff\dev\buildmas24\.env\Lib\site-packages\projit\template.py", line 5, in <module>       
    import pkg_resources
ModuleNotFoundError: No module named 'pkg_resources'
```

**Comment by john-hawkins** [comment]
Hey Geoff,

I am testing this and I am seeing issues related to **pip** dependencies with newer versions of python.
This post suggests that **pip** has problems deprecated classes in  **setuptools** from 3.12 onwards.
https://stackoverflow.com/questions/77364550/attributeerror-module-pkgutil-has-no-attribute-impimporter-did-you-mean

I managed to install and run projit on python 3.13 by upgrading pip inside the virtual environment like this:
```
python -m ensurepip --upgrade
python -m pip install projit
```

Other posts seem to be suggesting that using pip in this way is now recommended, as it avoids dependency issues between separate installs of python and pip. I will keep looking into this.

**Comment by claresloggett** [comment]
Just to add a comment, if I use conda for a new Python 3.13 install, i.e.
```
conda create -n projit python=3.13
pip install projit
```

I don't have any issues installing or running projit. `python -m pip` is sometimes needed if you're on a system where your version of the `pip` executable may not match your version of your `python` executable, but if there is a package manager looking after it for you, it should be no different to running `pip`.
